%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% keb 8/2011
% function to sum data from structures in MAP_ALL_DATA container
%
% 2011-10-07 keb - updated error message for metadata
%
% BUGS: If a timeseries (say S332D) is present in one model run but not in
% another, the script will not sum any of them. Anything that is a sum of 
% just cells is ok, but when summing structures there should be problems. 
% The fix is probably to iterate through timeseries for each model run 
% instead of doing them all at once.


function [ MAP_ALL_DATA ] = combine_modeled_timeseries_v0(MAP_ALL_DATA)

% pull out first cell to copy metadata from for transects:
try
   DATA_TMP = MAP_ALL_DATA(char('R046C116_OLy'));
catch
   fprintf('\nWARNING in combine_modeled_timeseries_v0 - could not get metadata for flowlines. Skipping these calculations.\n\n');
   return;
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Transect table of contents:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% C-111 transect:   xsect_C111_Q
% Context Rd:       xsect_ContextRd_Q
% TSB transect:     xsect_TSB_Q
% TT-NESS transect: xsect_TTNESS_Q
% TT-S12s transect: xsect_TTS12s_Q
% S343s transect:   xsect_S343s_Q
% Sbnd transect:    xsect_Sbnd_Q


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Transect definitions:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% C-111 transect:   xsect_C111_Q

% pull out and sum timeseries:
try
  TIMESERIES = 0;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R024C132_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R024C132_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R023C133_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R023C133_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R022C134_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R022C134_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R022C135_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C136_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C136_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C137_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C138_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R020C139_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R020C139_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R020C140_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R020C141_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R019C142_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R019C142_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R019C143_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R019C144_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R018C145_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R018C145_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R018C146_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R018C147_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R017C148_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R017C148_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R017C149_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R016C150_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R016C150_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R016C151_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R016C152_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R016C153_OLy')).TIMESERIES ;

  % copy metadata into data structure format:
  COMBINED_COMPUTED.NAME       = {'xsect_C111_Q'};
  COMBINED_COMPUTED.TIMESERIES = TIMESERIES;
  COMBINED_COMPUTED.TIMEVECTOR = DATA_TMP.TIMEVECTOR;
  COMBINED_COMPUTED.DFSTYPE    = DATA_TMP.DFSTYPE;
  COMBINED_COMPUTED.UNIT       = DATA_TMP.UNIT;

  % append new key and data structure to container
  MAP_ALL_DATA('xsect_C111_Q') = COMBINED_COMPUTED;
catch
  fprintf('\nWARNING - problem calculating model group: %s  - skipped', 'xsect_C111_Q');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Context Rd transect: xsect_ContextRd_Q

% pull out and sum timeseries:
try
  TIMESERIES = 0;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C098_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C099_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C100_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C101_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C102_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C103_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C104_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C105_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C106_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C107_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C108_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C109_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C110_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C111_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C112_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C113_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C114_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C115_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C116_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C117_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C118_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C119_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C120_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C121_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C122_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R080C123_OLy')).TIMESERIES ;

  % copy metadata into data structure format:
  COMBINED_COMPUTED.NAME       = {'xsect_ContextRd_Q'};
  COMBINED_COMPUTED.  TIMESERIES = TIMESERIES;
  COMBINED_COMPUTED.TIMEVECTOR = DATA_TMP.TIMEVECTOR;
  COMBINED_COMPUTED.DFSTYPE    = DATA_TMP.DFSTYPE;
  COMBINED_COMPUTED.UNIT       = DATA_TMP.UNIT;

  % append new key and data structure to container
  MAP_ALL_DATA('xsect_ContextRd_Q') = COMBINED_COMPUTED;
catch
  fprintf('\nWARNING - problem calculating model group: %s  - skipped', 'xsect_ContextRd_Q');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TSB transect:     xsect_TSB_Q

% pull out and sum timeseries:
try
  TIMESERIES = 0;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R049C111_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R048C112_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R048C113_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R048C113_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R047C114_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R047C115_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R047C115_OLx')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R046C116_OLy')).TIMESERIES;

  % copy metadata into data structure format:
  COMBINED_COMPUTED.NAME       = {'xsect_TSB_Q'};
  COMBINED_COMPUTED.  TIMESERIES = TIMESERIES;
  COMBINED_COMPUTED.TIMEVECTOR = DATA_TMP.TIMEVECTOR;
  COMBINED_COMPUTED.DFSTYPE    = DATA_TMP.DFSTYPE;
  COMBINED_COMPUTED.UNIT       = DATA_TMP.UNIT;

  % append new key and data structure to container
  MAP_ALL_DATA('xsect_TSB_Q') = COMBINED_COMPUTED;
catch
  fprintf('\nWARNING - problem calculating model group: %s  - skipped', 'xsect_TSB_Q');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TT-NESS transect: xsect_TTNESS_Q

% pull out and sum timeseries:
try
  TIMESERIES = 0;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C095_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C096_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C097_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C098_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C099_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C100_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C101_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C102_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C103_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C104_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C105_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C106_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C107_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C108_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C109_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C110_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C111_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C112_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C113_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C114_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C115_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C116_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C117_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C118_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C119_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C120_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C121_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C122_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C123_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C124_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C125_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C126_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C127_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C128_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C129_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C130_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C131_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C132_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C133_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C134_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C135_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C136_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C137_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C138_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C139_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C140_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C141_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C142_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C143_OLy')).TIMESERIES;

  % copy metadata into data structure format:
  COMBINED_COMPUTED.NAME       = {'xsect_TTNESS_Q'};
  COMBINED_COMPUTED.  TIMESERIES = TIMESERIES;
  COMBINED_COMPUTED.TIMEVECTOR = DATA_TMP.TIMEVECTOR;
  COMBINED_COMPUTED.DFSTYPE    = DATA_TMP.DFSTYPE;
  COMBINED_COMPUTED.UNIT       = DATA_TMP.UNIT;

  % append new key and data structure to container
  MAP_ALL_DATA('xsect_TTNESS_Q') = COMBINED_COMPUTED;
catch
  fprintf('\nWARNING - problem calculating model group: %s  - skipped', 'xsect_TTNESS_Q');
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TT-S12s transect: xsect_TTS12s_Q

% pull out and sum timeseries:
try
  TIMESERIES = 0;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C054_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C055_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C056_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C057_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C058_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C059_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C060_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C061_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C062_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C063_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C064_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C065_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C066_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C067_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C068_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C069_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C070_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C071_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C072_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C073_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C074_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C075_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C076_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C077_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C078_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C079_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C080_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C081_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C082_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C083_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C084_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C085_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C086_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C087_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C088_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C089_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C090_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C091_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C092_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C093_OLy')).TIMESERIES;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C094_OLy')).TIMESERIES;

  % copy metadata into data structure format:
  COMBINED_COMPUTED.NAME       = {'xsect_TTS12s_Q'};
  COMBINED_COMPUTED.  TIMESERIES = TIMESERIES;
  COMBINED_COMPUTED.TIMEVECTOR = DATA_TMP.TIMEVECTOR;
  COMBINED_COMPUTED.DFSTYPE    = DATA_TMP.DFSTYPE;
  COMBINED_COMPUTED.UNIT       = DATA_TMP.UNIT;

  % append new key and data structure to container
  MAP_ALL_DATA('xsect_TTS12s_Q') = COMBINED_COMPUTED;
catch
  fprintf('\nWARNING - problem calculating model group: %s  - skipped', 'xsect_TTS12s_Q');
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% S343s transect:   xsect_S343s_Q

% pull out and sum timeseries:
try
  TIMESERIES = 0;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C053_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R145C052_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R146C051_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R147C050_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R148C049_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R149C048_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R150C047_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R151C046_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R152C045_OLx')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R144C053_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R145C052_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R146C051_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R147C050_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R148C049_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R149C048_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R150C047_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R151C046_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R152C045_OLy')).TIMESERIES;

  % copy metadata into data structure format:
  COMBINED_COMPUTED.NAME       = {'xsect_S343s_Q'};
  COMBINED_COMPUTED.  TIMESERIES = TIMESERIES;
  COMBINED_COMPUTED.TIMEVECTOR = DATA_TMP.TIMEVECTOR;
  COMBINED_COMPUTED.DFSTYPE    = DATA_TMP.DFSTYPE;
  COMBINED_COMPUTED.UNIT       = DATA_TMP.UNIT;

  % append new key and data structure to container
  MAP_ALL_DATA('xsect_S343s_Q') = COMBINED_COMPUTED;

  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  % add a couple others
  MAP_ALL_DATA('xsect_S343strucs_Q') = COMBINED_COMPUTED;
  MAP_ALL_DATA('xsect_S343culverts_Q') = COMBINED_COMPUTED;
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


catch
  fprintf('\nWARNING - problem calculating model group: %s  - skipped', 'xsect_S343s_Q');
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Sbnd transect:    xsect_Sbnd_Q

% pull out and sum timeseries:
try
  TIMESERIES = 0;
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C043_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C044_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C045_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C046_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C047_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C048_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C049_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C050_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C051_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C052_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C053_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C054_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C055_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C056_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C057_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C058_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C059_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C060_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C061_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C062_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C063_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C064_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C065_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C066_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C067_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C068_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C069_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C070_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C071_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C072_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C073_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C074_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C075_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C076_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C077_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C078_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C079_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C080_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C081_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C082_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C083_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C084_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C085_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C086_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C087_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C088_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C089_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C090_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C091_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C092_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C093_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C094_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C095_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C096_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C097_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C098_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C099_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C100_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C101_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C102_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C103_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C104_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C105_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C106_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C107_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C108_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C109_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C110_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C111_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C112_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C113_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C114_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C115_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C116_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C117_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C118_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C119_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C120_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C121_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C122_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C123_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C124_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C125_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C126_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C127_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C128_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C129_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C130_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C131_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C132_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C133_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C134_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C135_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C136_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C137_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C138_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C139_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C140_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C141_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C142_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C143_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C144_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C145_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C146_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C147_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C148_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C149_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C150_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C151_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C152_OLy')).TIMESERIES; 
  TIMESERIES = TIMESERIES + (-1.0)*MAP_ALL_DATA(char('R021C153_OLy')).TIMESERIES;

  % copy metadata into data structure format:
  COMBINED_COMPUTED.NAME       = {'xsect_Sbnd_Q'};
  COMBINED_COMPUTED.  TIMESERIES = TIMESERIES;
  COMBINED_COMPUTED.TIMEVECTOR = DATA_TMP.TIMEVECTOR;
  COMBINED_COMPUTED.DFSTYPE    = DATA_TMP.DFSTYPE;
  COMBINED_COMPUTED.UNIT       = DATA_TMP.UNIT;

  % append new key and data structure to container
  MAP_ALL_DATA('xsect_Sbnd_Q') = COMBINED_COMPUTED;
catch
  fprintf('\nWARNING - problem calculating model group: %s  - skipped', 'xsect_Sbnd_Q');
end

end
